.PHONY: clean All

All:
	@echo "----------Building project:[ Guessing_Game - Debug ]----------"
	@cd "Guessing_Game" && "$(MAKE)" -f  "Guessing_Game.mk"
clean:
	@echo "----------Cleaning project:[ Guessing_Game - Debug ]----------"
	@cd "Guessing_Game" && "$(MAKE)" -f  "Guessing_Game.mk" clean
